# -*- coding: utf-8 -*-
"""BERT_Vietnamse_Sentiment_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/tranlinh102/BERT_Vietnamse_Sentiment_Assistant/blob/main/BERT_Vietnamse_Sentiment_Assistant.ipynb
"""

!pip install streamlit pyngrok transformers torch -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
# import sqlite3, datetime, os
# import re
# 
# # Xử lý biến thể tiếng Việt
# 
# VIET_VARIANTS = {
#     "rat": "rất",
#     "ratt": "rất",
#     "dc": "được",
#     "đc": "được",
#     "dcj": "được",
#     "hok": "không",
#     "hum": "hôm",
#     "hom": "hôm",
#     "vs": "với",
#     "k": "không",
#     "ko": "không",
#     "khong": "không",
#     "mn": "mọi người",
#     "ad": "admin",
# }
# 
# def normalize_vietnamese(text: str):
#     text = text.lower().strip()
# 
#     # thay biến thể bằng từ chuẩn
#     for k, v in VIET_VARIANTS.items():
#         pattern = r"\b" + re.escape(k) + r"\b"
#         text = re.sub(pattern, v, text)
# 
#     # xoá ký tự linh tinh (giữ dấu tiếng Việt)
#     text = re.sub(r"[^a-zA-Z0-9À-ỹ\s,.!?\-]", " ", text)
#     text = re.sub(r"\s+", " ", text).strip()
# 
#     # giới hạn 50 ký tự
#     if len(text) > 50:
#         text = text[:50].rstrip()
# 
#     return text
# 
# 
# # Load Model (cache)
# 
# model_name = "Zonecb/my-phobert-sentiment-v2"
# 
# @st.cache_resource
# def load_model():
#     tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=False)
#     model = AutoModelForSequenceClassification.from_pretrained(model_name)
#     clf = pipeline("text-classification", model=model, tokenizer=tokenizer)
#     return clf
# 
# def get_classifier():
#     return load_model()
# 
# classifier = get_classifier()
# 
# 
# # Map nhãn
# LABEL_MAP = {
#     "positive": "POSITIVE",
#     "negative": "NEGATIVE",
#     "neutral":  "NEUTRAL"
# }
# 
# 
# # SQLite
# def init_db():
#     conn = sqlite3.connect("sentiments.db")
#     cursor = conn.cursor()
#     cursor.execute("""
#     CREATE TABLE IF NOT EXISTS sentiments (
#         id INTEGER PRIMARY KEY AUTOINCREMENT,
#         text TEXT,
#         sentiment TEXT,
#         timestamp TEXT
#     )
#     """)
#     conn.commit()
#     return conn, cursor
# 
# conn, cursor = init_db()
# 
# def save_to_db(text, sentiment):
#     ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
#     cursor.execute("INSERT INTO sentiments(text, sentiment, timestamp) VALUES (?, ?, ?)",
#                    (text, sentiment, ts))
#     conn.commit()
# 
# def load_sentiment_records(limit, offset):
#     cursor.execute("SELECT * FROM sentiments ORDER BY timestamp DESC LIMIT ? OFFSET ?", (limit, offset))
#     return cursor.fetchall()
# 
# def get_total_sentiment_records():
#     cursor.execute("SELECT COUNT(*) FROM sentiments")
#     return cursor.fetchone()[0]
# 
# 
# # UI
# st.title("Phân Tích Cảm Xúc Văn Bản — PhoBERT")
# 
# user_text = st.text_area("Nhập câu cần phân tích cảm xúc:", height=150, key="input_text")
# 
# if st.button("Phân tích"):
#     if len(user_text.strip()) < 5:
#         st.warning("Văn bản quá ngắn.")
#     else:
#         # TIỀN XỬ LÝ TIẾNG VIỆT
#         clean_text = normalize_vietnamese(user_text)
# 
#         # chạy model
#         result = classifier(clean_text)[0]
#         raw_label = result["label"].lower()
#         score = result["score"]
# 
#         # rule: score < 0.5 → NEUTRAL
#         if score < 0.5:
#             sentiment = "NEUTRAL"
#         else:
#             sentiment = LABEL_MAP.get(raw_label, "NEUTRAL")
# 
#         save_to_db(clean_text, sentiment)
# 
#         # Display result with icon and color
#         if sentiment == "POSITIVE":
#             st.success(f"Kết quả: **Tích cực** (score={score:.4f})")
#         elif sentiment == "NEGATIVE":
#             st.error(f"Kết quả: **Tiêu cực** (score={score:.4f})")
#         else: # NEUTRAL
#             st.info(f"Kết quả: **Trung tính** (score={score:.4f})")
# 
# st.subheader("Lịch sử dự đoán gần đây")
# 
# # Initialize session state for display limit and collapse state
# if "display_limit" not in st.session_state:
#     st.session_state.display_limit = 50  # Initial display limit
# if "history_expanded" not in st.session_state:
#     st.session_state.history_expanded = True # Initial state is expanded
# 
# total_records = get_total_sentiment_records()
# 
# # Add a toggle button for expanding/collapsing history
# if st.session_state.history_expanded:
#     if st.button("Thu gọn lịch sử"):
#         st.session_state.history_expanded = False
#         st.rerun()
# else:
#     if st.button("Mở rộng lịch sử"):
#         st.session_state.history_expanded = True
#         st.rerun()
# 
# # Conditionally display records based on the expanded state
# if st.session_state.history_expanded:
#     records_to_display = load_sentiment_records(st.session_state.display_limit, 0)
# 
#     if not records_to_display:
#         st.write("Chưa có lịch sử phân tích.")
#     else:
#         st.write(f"Đã hiển thị {len(records_to_display)} trong tổng số {total_records} bản ghi.")
#         for r in records_to_display:
#             st.write(f"- `{r[3]}` | **{r[2]}** → {r[1]}")
# 
#         # Add a button to collapse to 50 records if more than 50 are displayed
#         if st.session_state.display_limit > 50:
#             if st.button("Thu gọn về 50 bản ghi"):
#                 st.session_state.display_limit = 50
#                 st.rerun()
# 
#         if st.session_state.display_limit < total_records:
#             remaining_to_load = min(50, total_records - st.session_state.display_limit)
#             if st.button(f"Tải thêm ({remaining_to_load} bản ghi)"):
#                 st.session_state.display_limit += 50  # Increase by 50 records
#                 st.rerun() # Rerun to update the display
# 
# 
# if st.button("Xoá toàn bộ dữ liệu"):
#     if os.path.exists("sentiments.db"):
#         os.remove("sentiments.db")
#         st.success("Đã xoá toàn bộ dữ liệu! Vui lòng reload ứng dụng.")
#         st.stop()

# Chạy Streamlit + ngrok trong Colab
from pyngrok import ngrok
import os
import time

# Set token ngrok
ngrok.set_auth_token("35hwjW82MBTs4MgHefNQVyfQDfw_4Tuwk82VXZv59obFo2Dd3")

# Mở tunnel trước
public_url = ngrok.connect(8501)
print("Ngrok URL:", public_url)

# Chạy Streamlit trong background
os.system("streamlit run app.py --server.port 8501 &")

# Chờ một chút để server khởi động
time.sleep(5)

print(f"Ứng dụng đang chạy: {public_url}")

# Ngắt kết nối tất cả các tunnel ngrok đang hoạt động
ngrok.kill()

print("Đã ngắt kết nối tất cả các tunnel ngrok.")